=== ravishankar2463/jaxbTutorial/src/main/resources/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListProductDTO">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="productDTO" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:long" name="eancode"/>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:int" name="price"/>
                            <xs:element type="xs:int" name="weight"/>
                            <xs:element type="xs:string" name="description"/>
                            <xs:element type="xs:int" name="quantity"/>
                            <xs:element type="xs:string" name="categoryName"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ravishankar2463/jaxbTutorial/target/classes/sample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ListProductDTO
        xsi:noNamespaceSchemaLocation="schema.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <productDTO>
        <eancode>1111111111111</eancode>
        <name>hamburger</name>
        <price>10</price>
        <weight>100</weight>
        <description>a nice hamburger</description>
        <quantity>1</quantity>
        <categoryName>meat</categoryName>
    </productDTO>
    <productDTO>
        <eancode>2111111111111</eancode>
        <name>banana</name>
        <price>6</price>
        <weight>100</weight>
        <description>a nice banana</description>
        <quantity>1</quantity>
        <categoryName> fruit</categoryName>
    </productDTO>
    <productDTO>
        <eancode>3111111111111</eancode>
        <name>apple</name>
        <price>10</price>
        <weight>100</weight>
        <description>a nice apple</description>
        <quantity>1</quantity>
        <categoryName>fruit</categoryName>
    </productDTO>
</ListProductDTO>
